export const STORAGE_KEYS = {
  USER_PROGRESS: 'user_progress',
  PRACTICE_SESSIONS: 'practice_sessions',
  GOALS: 'goals',
  GOAL_SUGGESTION_STATE: 'goal_suggestion_state',
  QUESTS: 'quests',
  ACHIEVEMENTS: 'achievements',
  WEEKLY_TARGET: 'weekly_target',
  REMINDER_SETTINGS: 'reminder_settings',
  ONBOARDING_COMPLETED: 'onboarding_completed',
  APP_RATING_STATE: 'app_rating_state',
  CELEBRATED_MILESTONES: 'celebrated_milestones',
  CUSTOM_CATEGORIES: 'custom_categories',
  SAVED_CHORDS: 'saved_chords',
} as const;
